apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orchestrator
resources:
  - serviceaccount.yaml
  - configmap-orchestrator-config.yaml
  - configmap-orchestrator-agents.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - bridge-ri/deployment.yaml
  - bridge-ri/service.yaml
  - bridge-ri/networkpolicy.yaml
labels:
  - pairs:
      app: orchestrator
