apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: orchestrator
  labels:
    app: orchestrator
    component: web
spec:
  type: ClusterIP
  selector:
    app: orchestrator
    component: web
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
